name: 'macos-dmg'
description: 'Package an app to a .dmg'
author: 'Turscar'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'disc'
  color: 'blue'

# Define your inputs here.
inputs:
  app:
    description: 'Path to Your.app'
    required: true
  dmg:
    description: 'Path to generate .dmg file'
    required: false
  title:
    description: 'Title of generated .dmg file'
    required: false
  icon-template:
    description: 'Template .icns file to generate .dmg icon'
    required: false
  icon:
    description: 'Icon file for .dmg icon'
    required: false
  background:
    description: 'Path to background image'
    required: false

runs:
  using: node20
  main: dist/index.js
